### ISSUE TITLE
Plan Meeting for Next Maptime - April

### ISSUE THREAD

**Issue by flippmoke** [maptimeokc/maptimeokc.github.io#4]
@jvrousseau Lets get something up here really soon for the next maptime, we are kind of late already putting up something. A. Plan out some speakers, B. post about it.

**Comment by jvrousseau** [comment]
@flippmoke I'll start some discussions on http://www.meetup.com/maptime-okc/ to fill the rest of the lightning talks.

I'll also add this month's meetup details

**Comment by jvrousseau** [comment]
added http://maptimeokc.github.io/event/2015/04/27/lightning-talks/ and http://www.meetup.com/Maptime-OKC/events/221918713/
